steps:
- id: build-image
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_IMAGE}:1.0.${BUILD_ID}', '-t', '${_IMAGE}:latest', '.' ]

- id: scan-image
  name: 'aquasec/trivy'
  args: [ 'image', '${_IMAGE}:latest', '--severity', 'CRITICAL' ]
  waitFor:
  - build-image

- id: push-image
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '--all-tags', '${_IMAGE}']
  waitFor:
  - build-image

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'cloudrunservice'
  - '--image'
  - '${_IMAGE}:latest'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'

substitutions:
    _IMAGE: 'gcr.io/${PROJECT_ID}/podinfo'

options:
    dynamic_substitutions: true